### ISSUE TITLE
Can't boot the VM on "vagrant up" command, virtualbox provider

### ISSUE THREAD

**Issue by SaltOfTheFlame** [slashr00t/vagrant-zabbix#1]
Can't boot the VM on "vagrant up" command, virtualbox provider
log:
...
==> server: Booting VM...
==> server: Waiting for machine to boot. This may take a few minutes...
    server: SSH address: 127.0.0.1:2200
    server: SSH username: vagrant
    server: SSH auth method: private key
    server: Warning: Remote connection disconnect. Retrying...
    server: Warning: Authentication failure. Retrying...
    server: Warning: Authentication failure. Retrying...
    server: Warning: Authentication failure. Retrying...
    server: Warning: Authentication failure. Retrying...
    server: Warning: Authentication failure. Retrying...
    server: Warning: Authentication failure. Retrying...
    server: Warning: Authentication failure. Retrying...
    server: Warning: Authentication failure. Retrying...
    server: Warning: Authentication failure. Retrying...
    server: Warning: Authentication failure. Retrying...
    server: Warning: Authentication failure. Retrying...
    server: Warning: Authentication failure. Retrying...
    server: Warning: Authentication failure. Retrying...
    server: Warning: Authentication failure. Retrying...
    server: Warning: Authentication failure. Retrying...
    server: Warning: Authentication failure. Retrying...
...

**Comment by cloudowski** [comment]
This may happen if you use older version of Vagrant. Please make sure that you're using something newer - I've also added this requirement to Vagrantfile.

**Comment by SaltOfTheFlame** [comment]
Thanks! that worked! i had 1.8.5 version and updated to 1.8.6 and now everything works
