### ISSUE TITLE
getting errors and warnings on "vagrant up" and "vagrant provision" (last one is "==> server: Error: Could not find a suitable provider for mysql_datadir" )

### ISSUE THREAD

**Issue by SaltOfTheFlame** [slashr00t/vagrant-zabbix#2]
р

**Comment by SaltOfTheFlame** [comment]
P.S.: I got this problem on virtualbox , if it matters

**Comment by cloudowski** [comment]
Please check the newest version - I've updated zabbix to 3.2 and fixed most of the issues.

**Comment by SaltOfTheFlame** [comment]
still not working ((( but log changed:
.....
==> server: Notice: /Stage[main]/Zabbix::Server/Zabbix::Startup[zabbix-server]/File[/etc/systemd/system/zabbix-server.service]: Dependency Package[zabbix-server-pgsql] has failures: true
==> server: Error: Execution of '/bin/yum -d 0 -e 0 -y install zabbix-server-pgsql' returned 1: warning: /var/cache/yum/x86_64/7/Zabbix_nonsupported_7_x86_64/packages/iksemel-1.4-2.el7.centos.x86_64.rpm: Header V4 DSA/SHA1 Signature, key ID 79ea5ed4: NOKEY
==> server: Public key for iksemel-1.4-2.el7.centos.x86_64.rpm is not installed
==> server: 
==> server: 
==> server: Error downloading packages:
==> server:   fping-3.10-1.el7.x86_64: [Errno 256] No more mirrors to try.
==> server: Error: /Stage[main]/Zabbix::Server/Package[zabbix-server-pgsql]/ensure: change from absent to present failed: Execution of '/bin/yum -d 0 -e 0 -y install zabbix-server-pgsql' returned 1: warning: /var/cache/yum/x86_64/7/Zabbix_nonsupported_7_x86_64/packages/iksemel-1.4-2.el7.centos.x86_64.rpm: Header V4 DSA/SHA1 Signature, key ID 79ea5ed4: NOKEY
==> server: Public key for iksemel-1.4-2.el7.centos.x86_64.rpm is not installed
==> server: 
==> server: 
==> server: Error downloading packages:
==> server:   fping-3.10-1.el7.x86_64: [Errno 256] No more mirrors to try.
==> server: Warning: /Stage[main]/Zabbix::Database::Postgresql/File[/root/.pgpass]: Skipping because of failed dependencies
==> server: Warning: /Stage[main]/Zabbix::Database::Postgresql/Exec[update_pgpass]: Skipping because of failed dependencies
==> server: Warning: /Stage[main]/Zabbix::Server/File[/etc/zabbix/zabbix_server.conf]: Skipping because of failed dependencies
==> server: Warning: /Stage[main]/Zabbix::Server/File[/etc/zabbix/zabbix_server.conf.d]: Skipping because of failed dependencies
....... etc.

**Comment by SaltOfTheFlame** [comment]
I can move that exception to other issue
